import test from'node:test';
import assert from'node:assert/strict';
import{escapeXml,textItemsToLines,linesToParagraphs,analyzeTextPage,ocrTextToParagraphs,buildDocumentXml,buildDocxParts}from'../assets/js/pdf-to-word-core.mjs';

test('xml escaping removes invalid chars',()=>assert.equal(escapeXml('<A&B>\u0001'),'&lt;A&amp;B&gt;'));
test('text items group into readable lines',()=>{const lines=textItemsToLines([{str:'Hello',transform:[12,0,0,12,10,100],width:28,fontName:'Arial'},{str:'world',transform:[12,0,0,12,45,100],width:30,fontName:'Arial'},{str:'Next',transform:[12,0,0,12,10,80],width:25,fontName:'Arial-Bold'}]);assert.equal(lines.length,2);assert.equal(lines[0].text,'Hello world');assert.equal(lines[1].text,'Next');assert.equal(lines[1].bold,true);});
test('wrapped lines become paragraphs',()=>{const p=linesToParagraphs([{text:'This is a wrapped',y:100,xMin:10,fontSize:10,bold:false,italic:false,wideGaps:0},{text:'sentence.',y:88,xMin:10,fontSize:10,bold:false,italic:false,wideGaps:0},{text:'New block',y:60,xMin:10,fontSize:10,bold:false,italic:false,wideGaps:0}]);assert.equal(p.length,2);assert.equal(p[0].text,'This is a wrapped sentence.');});
test('scan and complex layout diagnostics',()=>{assert.equal(analyzeTextPage([],600).scannedLikely,true);const lines=Array.from({length:10},(_,i)=>({text:'abc',xMin:i%2?280:20,wideGaps:i<4?1:0}));assert.equal(analyzeTextPage(lines,600).complexLayout,true);});
test('ocr text converts to paragraphs',()=>assert.deepEqual(ocrTextToParagraphs('First line\nsecond line\n\nNext'),[{text:'First line second line',fontSize:11,bold:false,italic:false,heading:false,bullet:false},{text:'Next',fontSize:11,bold:false,italic:false,heading:false,bullet:false}]));
test('docx xml contains paragraphs and page breaks',()=>{const xml=buildDocumentXml([{paragraphs:[{text:'Page one',fontSize:11}]},{paragraphs:[{text:'Page two',fontSize:11}]}]);assert.match(xml,/Page one/);assert.match(xml,/w:type="page"/);assert.match(xml,/Page two/);const parts=buildDocxParts([{paragraphs:[{text:'Hi',fontSize:11}]}],'Test');assert.ok(parts['[Content_Types].xml']);assert.ok(parts['word/document.xml']);assert.match(parts['docProps/core.xml'],/Test/);});
