import test from'node:test';import assert from'node:assert/strict';import{passportSize,packRects,contactSheetPlan,posterPlan,posterPlanForSize,PAPER}from'../assets/js/print-layout-core.mjs';
test('US passport preset is 600px at 300dpi',()=>{const s=passportSize('us',300);assert.equal(s.widthPx,600);assert.equal(s.heightPx,600)});
test('4x6 sheet packs six US passport photos',()=>{const s=passportSize('us',300),p=packRects(PAPER.photo4x6.width,PAPER.photo4x6.height,s.widthPt,s.heightPt,{margin:0,gap:0});assert.equal(p.count,6)});
test('contact sheet grid count',()=>{const p=contactSheetPlan(PAPER.letter.width,PAPER.letter.height,3,4);assert.equal(p.perPage,12)});
test('poster plan creates requested tiles',()=>{const p=posterPlan({imageWidth:1200,imageHeight:800,pageWidth:612,pageHeight:792,cols:2,rows:3,overlap:18});assert.equal(p.pageCount,6);assert.equal(p.tiles.at(-1).col,1)});
test('exact poster size derives page grid',()=>{const p=posterPlanForSize({imageWidth:1200,imageHeight:800,pageWidth:612,pageHeight:792,posterWidth:1000,posterHeight:1400,overlap:18});assert.equal(p.cols,2);assert.equal(p.rows,2);assert.equal(p.pageCount,4)});
test('expanded poster paper sizes are available',()=>{assert.ok(PAPER.a3.width>PAPER.a4.width);assert.ok(PAPER.legal.height>PAPER.letter.height);assert.ok(PAPER.tabloid.width>PAPER.letter.width)});
test('poster plan reports rows and columns',()=>{const p=posterPlan({imageWidth:1200,imageHeight:800,pageWidth:612,pageHeight:792,cols:3,rows:2,overlap:18});assert.equal(p.cols,3);assert.equal(p.rows,2)});

import{imagePdfRasterPlan,formatBytes}from'../assets/js/image-pdf-core.mjs';
test('image PDF smart raster downsizes oversized fixed-page images without upscaling',()=>{const p=imagePdfRasterPlan({sourceWidth:6000,sourceHeight:4000,pageWidth:PAPER.a4.width,pageHeight:PAPER.a4.height,margin:18,fit:'contain',pageMode:'a4',profile:'smart'});assert.ok(p.rasterWidth<6000);assert.ok(p.rasterHeight<4000);assert.ok(p.effectiveDpi>=200);assert.equal(p.reduced,true);const small=imagePdfRasterPlan({sourceWidth:800,sourceHeight:600,pageWidth:PAPER.a4.width,pageHeight:PAPER.a4.height,margin:18,fit:'contain',pageMode:'a4',profile:'high'});assert.equal(small.rasterWidth,800);assert.equal(small.rasterHeight,600)});
test('image PDF match-image smart profile caps extreme source dimensions',()=>{const p=imagePdfRasterPlan({sourceWidth:8000,sourceHeight:6000,pageWidth:4000,pageHeight:3000,pageMode:'image',profile:'smart'});assert.ok(p.rasterWidth<=3200);assert.ok(p.rasterWidth*p.rasterHeight<=9000000);assert.equal(formatBytes(1048576),'1.00 MB')});
